export const activeUsers = [
  {
    id: '1',
    name: 'Isabelle',
    avatar: require('../../assets/images/ChatScreen/avt1.png'),
  },
  {
    id: '2',
    name: 'Ethan',
    avatar: require('../../assets/images/ChatScreen/avt2.png'),
  },
  {
    id: '3',
    name: 'Harper',
    avatar: require('../../assets/images/ChatScreen/avt3.png'),
  },
  {
    id: '4',
    name: 'Alexander',
    avatar: require('../../assets/images/ChatScreen/avt4.png'),
  },
];

export const recentChats = [
  {
    id: 'r1',
    user: 'Alexander',
    avatar: require('../../assets/images/ChatScreen/avt4.png'),
    message: "Hey, what's up?",
    time: '4 min',
    unreadCount: 1,
  },
  {
    id: 'r2',
    user: 'Isabelle',
    avatar: require('../../assets/images/ChatScreen/avt1.png'),
    message: 'That sounds cool. What...',
    time: '35 min',
    unreadCount: 3,
  },
  {
    id: 'r3',
    user: 'Harper',
    avatar: require('../../assets/images/ChatScreen/avt3.png'),
    message: 'I like to do a lot of different...',
    time: '39 min',
    unreadCount: 5,
  },
  {
    id: 'r4',
    user: 'Ethan',
    avatar: require('../../assets/images/ChatScreen/avt2.png'),
    message: "That's awesome.",
    time: 'Today',
    unreadCount: 0,
  },
  {
    id: 'r5',
    user: 'Isabelle',
    avatar: require('../../assets/images/ChatScreen/avt1.png'),
    message: 'Did you finish the task?',
    time: '2 hr',
    unreadCount: 2,
  },
  {
    id: 'r6',
    user: 'Ethan',
    avatar: require('../../assets/images/ChatScreen/avt2.png'),
    message: 'Let’s catch up later!',
    time: 'Yesterday',
    unreadCount: 0,
  },
  {
    id: 'r7',
    user: 'Harper',
    avatar: require('../../assets/images/ChatScreen/avt3.png'),
    message: 'Just sent the email.',
    time: '1 hr',
    unreadCount: 1,
  },
  {
    id: 'r8',
    user: 'Alexander',
    avatar: require('../../assets/images/ChatScreen/avt4.png'),
    message: 'Ping me when free!',
    time: '5 hr',
    unreadCount: 4,
  },
  {
    id: 'r9',
    user: 'Isabelle',
    avatar: require('../../assets/images/ChatScreen/avt1.png'),
    message: 'Yup, that’s confirmed.',
    time: '3 hr',
    unreadCount: 0,
  },
  {
    id: 'r10',
    user: 'Ethan',
    avatar: require('../../assets/images/ChatScreen/avt2.png'),
    message: 'Thanks!',
    time: 'Just now',
    unreadCount: 1,
  },
];
