const accounts = [
    {
        id: 1,
        username: 'Abc',
        password: '123',
        avatar: require('../../images/avatar_01.jpg'),
        name: 'Nguyễn Văn A',
        email: 'vana@gmail.com',
        birth: '1990-02-22',
        country: 'Vietnam',
        point: 1200,
    },
    {
        id: 2,
        username: 'darkKnight',
        password: '123',
        avatar: require('../../images/avatar_02.jpg'),
        name: 'Trần Thị B',
        email: 'tranb@gmail.com',
        birth: '1992-06-15',
        country: 'Vietnam',
        point: 1500,
    },
    {
        id: 3,
        username: 'whiteQueen',
        password: '123',
        avatar: require('../../images/avatar_03.jpg'),
        name: 'Lê Thị C',
        email: 'lec@gmail.com',
        birth: '1995-08-30',
        country: 'United States',
        point: 2100,
    },
    {
        id: 4,
        username: 'bishopMove',
        password: '123',
        avatar: require('../../images/avatar_04.jpg'),
        name: 'Phạm Văn D',
        email: 'phamd@gmail.com',
        birth: '1991-12-12',
        country: 'Canada',
        point: 1800,
    },
];

const friends = [
    {
        idAccount: 1,
        idFriend: 2,
        usernameFriend: 'darkKnight',
        avatarFriend: require('../../images/avatar_02.jpg'),
        nameFriend: 'Trần Thị B',
        emailFriend: 'tranb@gmail.com',
        birthFriend: '1992-06-15',
        countryFriend: 'Vietnam',
        pointFriend: 1500,
    },
    {
        idAccount: 1,
        idFriend: 3,
        usernameFriend: 'whiteQueen',
        avatarFriend: require('../../images/avatar_03.jpg'),
        nameFriend: 'Lê Thị C',
        emailFriend: 'lec@gmail.com',
        birthFriend: '1995-08-30',
        countryFriend: 'United States',
        pointFriend: 2100,
    },
    {
        idAccount: 2,
        idFriend: 1,
        usernameFriend: 'chessMaster01',
        avatarFriend: require('../../images/avatar_01.jpg'),
        nameFriend: 'Nguyễn Văn A',
        emailFriend: 'vana@gmail.com',
        birthFriend: '1990-02-22',
        countryFriend: 'Vietnam',
        pointFriend: 1200,
    },
    {
        idAccount: 2,
        idFriend: 4,
        usernameFriend: 'bishopMove',
        avatarFriend: require('../../images/avatar_04.jpg'),
        nameFriend: 'Phạm Văn D',
        emailFriend: 'phamd@gmail.com',
        birthFriend: '1991-12-12',
        countryFriend: 'Canada',
        pointFriend: 1800,
    },
];

export { accounts, friends };
